### ISSUE TITLE
tag-manager / stacks?

### ISSUE THREAD

**Issue by orchid00** [lvclark/tagdigger#1]
Hi, 
I would like to know, what version of stacks has been tested with tag-manager? 

I'm using TagDigger v. 1.0 Tag Manager
and selected: 5: Stacks catalog
I am getting the following error: Files in wrong format.
with the files output from stacks v 1.41

**Comment by lvclark** [comment]
It has been tested with Stacks 1.2.  Just now I tested some of my own files from Stacks 1.4 and I see that they are not readable.  I'll take a look to see how the format has changed, and also add support for the files to be Gzipped.  Thanks for your interest, and thanks for finding the bug!

**Comment by lvclark** [comment]
It turns out that Stacks 1.4 adds a comment line at the beginning of the file, which TagDigger wasn't expecting.  You will still have to unzip the catalog files before using them with TagDigger, but it should be working now.  I am going to leave this open for the time being since I would like to add support for GZ formatted Stacks files.

**Comment by orchid00** [comment]
Thanks for your quick reply Lindsay, I will test again on Monday and let you know how I go.
Will probably be OK to ask here. Do you input the catalog instead of the three files that are asked, that is snps.tsv, alleles.tsv and the tags.tsv. I will guess that the catalog has everything the program is looking for?

**Comment by lvclark** [comment]
I'm not sure what you are asking since cstacks generates those three files, and together they make up the catalog.  One has the reference tag sequence, one has the positions of SNPs, and one has the combinations of SNP alleles that make up the actual haplotypes observed in the dataset.  All three are needed together in order to reconstruct the expected tag sequences.

**Comment by orchid00** [comment]
What you say is correct: " cstacks generates those three files, and together they make up the catalog."
So I was just wondering, that instead of " All three are needed together in order to reconstruct the expected tag sequences." we could just use the catalog instead. 
But don't worry about.

**Comment by lvclark** [comment]
I have finally gotten around to fixing it so that Stacks catalog files are accepted in unzipped or gzipped format.
