### ISSUE TITLE
Marker names must not contain underscores.

### ISSUE THREAD

**Issue by orchid00** [lvclark/tagdigger#2]
Hi, 

I was just wondering if the requirement of tag files:
"Marker names must not contain underscores" this is too bothersome to change?

Most if not all my markers have underscores. Is there any specific reason why this is not allowed?

Thanks!

**Comment by lvclark** [comment]
Yes, there is a very good reason!  TagDigger names tags by combining the marker name and allele name and separating them by an underscore.  Therefore marker names can't have underscores because the software would not be able to properly parse the tag names back out into markers and alleles.  If it wasn't underscores, I would have to choose some other character to delimit marker and allele names and therefore not allow in marker names.
